services:
  # PHP-FPM
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    working_dir: /var/www
    volumes:
      - ./www:/var/www
    environment:
      XDEBUG_MODE: debug
    depends_on:
      - db
      - redis
    networks:
      - app-network

  # PostgreSQL 16 with pgvector
  db:
    image: pgvector/pgvector:pg16
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  # Nginx (Alpine)
  nginx:
    image: nginx:stable-alpine
    container_name: php-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app-network

volumes:
  db_data:
  redis_data:

networks:
  app-network:
    driver: bridge